CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS expenses (
    expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_id varchar(128) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    family varchar(256) NOT NULL,
    amount real NOT NULL,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (expense_id)
);