CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS families (
    family_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    family_name varchar(255) NOT NULL,
    PRIMARY KEY (family_id)
);

CREATE TABLE IF NOT EXISTS family_users (
    family_id BIGINT NOT NULL REFERENCES families (family_id),
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    PRIMARY KEY (family_id, user_id)
);

CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_name varchar(255),
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS expenses (
    expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_id BIGINT NOT NULL REFERENCES categories (category_id),
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    family_id BIGINT NOT NULL REFERENCES families,
    PRIMARY KEY (expense_id)
);